spring:
  datasource:
    url: jdbc:mysql://localhost/sarriola?serverTimezone=UTC
    username: root
    password: boquita
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
